create table if not exists adapter_poll_events (
  id bigint generated by default as identity primary key,
  adapter_id text not null,
  observed_at timestamptz not null,
  record_count integer not null,
  summary text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_adapter_poll_events_adapter_observed
  on adapter_poll_events (adapter_id, observed_at desc);
